# 
site_configs:
  site_name: doc share
  site_keywords: doc share
  site_default_title: doc share
  site_closed: false
  site_closed_description: "system maintaining..."

#
categories:
  "教育资源":
    - 考试资源
    - 小学初中
    - 高中教育
    - 高等教育
    - 外语学习
    - 学术研究
    - 其他教育资料
  "经济管理":
    - 战略管理
    - 市场营销
    - 企业制度
    - 行业分析
    - 人力资源
    - 生产运营
    - 财会税务
    - 项目管理
    - 经济金融
    - 专利
  "娱乐生活":
    - 电子书籍
    - 生活百科
    - 爆笑
    - 图片
  "IT资料":
    - 常用软件
    - 电子通讯
    - 软件工程
    - 解决方案
    - 专题技术
    - 手机软件
    - 源代码
    - IT书籍
    - 硬件技术
    - 电信技术
    - IT行业分析
  "专业资料":
    - 贸易
    - 服务
    - 农业
    - 医药
    - 体育
    - 法律
    - 环境
    - 宗教
    - 心理学
    - 基础科学
    - 广告媒体
    - 军事政治
    - 矿业冶金
    - 交通运输
    - 水利电力
    - 畜牧养殖
    - 艺术戏曲
    - 地理考古
    - 民族社会
    - 语言、文化
    - 机械、化工
    - 教育、出版
    - 哲学、历史
    - 工程建筑、房产
  "游戏资料":
    - 游戏下载
    - 单机游戏
    - 剑侠世界
    - 征途
    - 赤壁
    - 问道
    - 诛仙
    - 巨人
    - 口袋西游
    - 魔力宝贝Ⅱ
    - 侠义道
    - 蜀山OL
    - 西游Q记
    - 封神榜Ⅱ
  "办公文书":
    - 企业文书
    - 个人文书
    - 文档模板
    - 演讲稿
    - 求职简历

# 
repositories_git_store_paths:
  - <%= Rails.root.join("repositories_git_base1").to_s %>
  - <%= Rails.root.join("repositories_git_base2").to_s %>

user_username_exclusion_in: "home users repositories sessions reset_passwords auth account dashboard admin superuser superadmin search blog feedbacks"