# 
site_configs:
  site_name: doc share
  site_keywords: doc share
  site_default_title: doc share
  site_closed: false
  site_closed_description: "system maintaining..."

# 
repositories_git_store_paths:
  - <%= Rails.root.join("repositories_git_base1").to_s %>
  - <%= Rails.root.join("repositories_git_base2").to_s %>

user_username_exclusion_in: "home users repositories sessions reset_passwords auth account dashboard admin superuser superadmin"