project:
  name: doc share

web:
  head:
    meta:
      keywords: doc share
    title: doc share

sys:
  repo:
    base_dir: <%= File.join(RAILS_ROOT, "repo") %>

backups_db_backup_local_dir: <%= File.join(RAILS_ROOT, "backups") %>