common: &common
  ngram_len: 1
  ngram_chars: "U+3000..U+2FA1F"
  bin_path: /usr/local/coreseek/bin
  searchd_binary_name: searchd
  indexer_binary_name: indexer

development:
  <<: *common
test:
  <<: *common
production:
  <<: *common
